name: testing_mvvm_flutter
description: Testing MVVM in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  #Riverpod
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  graphql: ^5.1.3


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  swipe_refresh: ^1.0.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
